PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Detect dotfile path
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

function source_if_present(){
  local file="$1"
  [[ -f $file ]] && source "$file"
}

# Source Perlbrew
source_if_present ~/perl5/perlbrew/etc/bashrc

# Source Pyenv and Pyenv-virtualenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Source scripts and helper functions
source_if_present $(brew --prefix)/etc/bash_completion
source_if_present $HOME/.rvm/scripts/rvm
source_if_present $DIR/scripts/alias_completion.sh
source_if_present $DIR/scripts/git-niceness.sh
source_if_present $DIR/scripts/git-prompt.sh
source_if_present /usr/local/etc/bash_completion.d/git-completion.bash

# Source Configs
source_if_present $DIR/bash_config
source_if_present $DIR/bash_aliases

alias_completion
